#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function main() {
  console.log('\n======================================================');
  console.log(' 🧙‍♂️ Personal Finance Telegram Bot - Interactive Setup Wizard');
  console.log('======================================================\n');

  console.log('ตัวช่วยนี้จะพาคุณตั้งค่าตัวแปรใน .env ทีละขั้นตอนครับ\n');

  const envPath = path.resolve(process.cwd(), '.env');
  const existingEnv = fs.existsSync(envPath) ? fs.readFileSync(envPath, 'utf-8') : '';

  // 1. Telegram Bot Token
  console.log('📌 ขั้นตอนที่ 1: Telegram Bot Token');
  console.log('   (รับได้จาก @BotFather ใน Telegram)');
  const botToken = (await question('   ใส่ TELEGRAM_BOT_TOKEN: ')).trim();

  // 2. Authorized Telegram User ID
  console.log('\n📌 ขั้นตอนที่ 2: Telegram User ID ของคุณ');
  console.log('   (ดูตัวเลข ID ได้จาก @userinfobot ใน Telegram)');
  const userId = (await question('   ใส่ AUTHORIZED_TELEGRAM_USER_ID: ')).trim();

  // 3. Gemini API Key
  console.log('\n📌 ขั้นตอนที่ 3: Google Gemini API Key (ฟรี)');
  console.log('   (รับได้จาก https://aistudio.google.com/)');
  const geminiKey = (await question('   ใส่ GEMINI_API_KEY: ')).trim();

  // 4. Google Sheet ID
  console.log('\n📌 ขั้นตอนที่ 4: Google Spreadsheet ID');
  console.log('   (ดูจาก URL ของ Google Sheet: https://docs.google.com/spreadsheets/d/{ID}/edit)');
  const sheetId = (await question('   ใส่ GOOGLE_SHEET_ID: ')).trim();

  // 5. Service Account Key File
  console.log('\n📌 ขั้นตอนที่ 5: ไฟล์คีย์ Google Service Account JSON');
  console.log('   (สร้างจาก Google Cloud Console > IAM & Admin > Service Accounts > Keys)');
  let keyPath = (await question('   ใส่ที่อยู่ไฟล์ (กด Enter เพื่อใช้ ./service-account.json): ')).trim();
  if (!keyPath) keyPath = './service-account.json';

  const envContent = `# Auto-generated by Setup Wizard
TELEGRAM_BOT_TOKEN=${botToken}
AUTHORIZED_TELEGRAM_USER_ID=${userId}
GEMINI_API_KEY=${geminiKey}
GEMINI_MODEL=gemini-2.5-flash
GOOGLE_SHEET_ID=${sheetId}
GOOGLE_SERVICE_ACCOUNT_KEY_FILE=${keyPath}
TIMEZONE=Asia/Bangkok
DEFAULT_ACCOUNT=K PLUS
REMINDER_TIME=20:00
SECOND_REMINDER_TIME=22:00
`;

  fs.writeFileSync(envPath, envContent, 'utf-8');
  console.log('\n✅ บันทึกการตั้งค่าลงไฟล์ .env เรียบร้อยแล้ว!');

  console.log('\n⚠️ อย่าลืม:');
  console.log('1. นำไฟล์ Service Account JSON มาวางที่ตำแหน่ง:', keyPath);
  console.log('2. แชร์ Google Sheet ให้กับ email ของ Service Account โดยให้สิทธิ์ "Editor"');
  console.log('\n🚀 เริ่มใช้งานบอทได้ทันทีด้วยคำสั่ง:');
  console.log('   npm run dev\n');

  rl.close();
}

main().catch(console.error);

